# Generated by Django 5.2.17 on 2026-09-13 02:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.TextField()),
                ("url_hash", models.CharField(max_length=64, unique=True)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("published_at", models.DateTimeField(null=True)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                ("breaking", models.BooleanField(default=False)),
                ("imported", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("quota", models.PositiveIntegerField(default=3)),
                ("weight", models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="DomainLease",
            fields=[
                ("hostname", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("until", models.DateTimeField(default=django.utils.timezone.now)),
                ("owner", models.CharField(blank=True, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name="StoryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Tombstone",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArticleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("title", models.TextField()),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=500)),
                ("title_zh", models.TextField(blank=True)),
                ("summary_zh", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("meaningful", models.BooleanField(default=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="news.article",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="current",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for",
                to="news.articleversion",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="news.category"
            ),
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="favourite",
                        to="news.articleversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=2048, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("interval_seconds", models.PositiveIntegerField(default=600)),
                ("boost_until", models.DateTimeField(blank=True, null=True)),
                ("next_fetch", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("etag", models.TextField(blank=True)),
                ("modified", models.TextField(blank=True)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("last_success", models.DateTimeField(null=True)),
                ("last_status", models.CharField(blank=True, max_length=40)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="news.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrawlRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("job_key", models.CharField(max_length=240)),
                ("status", models.CharField(max_length=30)),
                ("http_status", models.IntegerField(default=0)),
                ("parsed", models.PositiveIntegerField(default=0)),
                ("added", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("duplicate", models.PositiveIntegerField(default=0)),
                ("elapsed_ms", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("feed", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="news.feed")),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="feed",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="news.feed"),
        ),
        migrations.CreateModel(
            name="FeedIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identity", models.CharField(max_length=64)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="news.article",
                    ),
                ),
                ("feed", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="news.feed")),
            ],
        ),
        migrations.CreateModel(
            name="HourStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hour", models.DateTimeField()),
                ("requests", models.PositiveIntegerField(default=0)),
                ("successes", models.PositiveIntegerField(default=0)),
                ("parsed", models.PositiveIntegerField(default=0)),
                ("added", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("duplicate", models.PositiveIntegerField(default=0)),
                ("elapsed_ms", models.BigIntegerField(default=0)),
                ("feed", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="news.feed")),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="news.storygroup"
            ),
        ),
        migrations.AddConstraint(
            model_name="articleversion",
            constraint=models.UniqueConstraint(
                fields=("article", "fingerprint"), name="version_content_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedidentity",
            constraint=models.UniqueConstraint(fields=("feed", "identity"), name="feed_identity_unique"),
        ),
        migrations.AddConstraint(
            model_name="hourstat",
            constraint=models.UniqueConstraint(fields=("hour", "feed"), name="hour_feed_unique"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["-first_seen", "-id"], name="news_articl_first_s_bf2629_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["feed", "-first_seen"], name="news_articl_feed_id_76566a_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["category", "-first_seen"], name="news_articl_categor_6b1858_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["updated_at"], name="news_articl_updated_9c27ed_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="news_articl_search__6fe81f_gin"
            ),
        ),
    ]
