# Generated by Django 5.2.17 on 2026-09-13 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="UsageDay",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                ("used", models.PositiveIntegerField(default=0)),
                ("reserved", models.PositiveIntegerField(default=0)),
                ("estimated", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("capability", models.CharField(max_length=40)),
                ("model", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(default="1", max_length=20)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("output", models.JSONField(default=dict)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("error", models.CharField(blank=True, max_length=200)),
                (
                    "version",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="news.articleversion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role", models.CharField(max_length=20)),
                ("text", models.TextField()),
                ("evidence", models.JSONField(default=list)),
                ("status", models.CharField(default="completed", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.conversation",
                    ),
                ),
            ],
        ),
    ]
