# Generated by Django 5.2.17 on 2026-09-23 00:34

from django.db import migrations, models
from django.utils import timezone


def account_for_existing_usage(apps, schema_editor):
    usage_day = apps.get_model("ai", "UsageDay")
    site_settings = apps.get_model("core", "SiteSettings")
    config = site_settings.objects.filter(pk=1).first()
    if not config:
        return
    day = usage_day.objects.filter(day=timezone.localdate()).first()
    if day and day.used and not day.lane_used:
        day.lane_used = {
            "legacy": day.used,
            "event": int(config.ai_daily_tokens * 0.20),
            "backfill": int(config.ai_daily_tokens * 0.10),
        }
        day.save(update_fields=["lane_used"])


def clear_false_japanese_localizations(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE news_articleversion
               SET title_zh = CASE WHEN title_zh = title AND title ~ '[ぁ-んァ-ン]' THEN '' ELSE title_zh END,
                   summary_zh = CASE WHEN summary_zh = summary AND summary ~ '[ぁ-んァ-ン]' THEN '' ELSE summary_zh END
             WHERE (title_zh = title AND title ~ '[ぁ-んァ-ン]')
                OR (summary_zh = summary AND summary ~ '[ぁ-んァ-ン]')
        """)
        cursor.execute("""
            UPDATE briefs_briefitem
               SET title_zh = CASE WHEN title_zh = title AND title ~ '[ぁ-んァ-ン]' THEN '' ELSE title_zh END,
                   summary_zh = CASE WHEN summary_zh = summary AND summary ~ '[ぁ-んァ-ン]' THEN '' ELSE summary_zh END
             WHERE (title_zh = title AND title ~ '[ぁ-んァ-ン]')
                OR (summary_zh = summary AND summary ~ '[ぁ-んァ-ン]')
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('core', '0005_alter_sitesettings_ai_daily_tokens'),
        ('briefs', '0002_briefitem_localized_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageday',
            name='lane_reserved',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usageday',
            name='lane_used',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(account_for_existing_usage, migrations.RunPython.noop),
        migrations.RunPython(clear_false_japanese_localizations, migrations.RunPython.noop),
    ]
