# Generated by Django 5.2.17 on 2026-09-13 02:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.TextField()),
                ("report", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ("briefing_times", models.JSONField(default=list)),
                ("max_items", models.PositiveIntegerField(default=20)),
                ("source_limit", models.PositiveIntegerField(default=2)),
                ("retention_days", models.PositiveIntegerField(default=180)),
                ("ai_model", models.CharField(default="deepseek-flash", max_length=100)),
                ("ai_daily_tokens", models.PositiveIntegerField(default=200000)),
                ("ai_concurrency", models.PositiveIntegerField(default=1)),
                ("db_budget_gb", models.FloatField(default=16)),
                ("soft_free_gb", models.FloatField(default=8)),
                ("hard_free_gb", models.FloatField(default=6)),
                ("last_schedule", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_backup", models.DateTimeField(null=True)),
                ("storage", models.JSONField(default=dict)),
                ("paused", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ImportMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=300, unique=True)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "article",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="news.article"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("key", models.CharField(max_length=240, unique=True)),
                ("queue", models.CharField(db_index=True, max_length=20)),
                ("kind", models.CharField(max_length=40)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("priority", models.IntegerField(default=100)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lease_until", models.DateTimeField(null=True)),
                ("owner", models.UUIDField(null=True)),
                ("result", models.JSONField(default=dict)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(null=True)),
                ("articles", models.ManyToManyField(blank=True, to="news.article")),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["queue", "status", "available_at", "priority"],
                        name="core_job_queue_cbf58a_idx",
                    )
                ],
            },
        ),
    ]
