# Generated by Django 5.2.17 on 2026-09-23 00:34

from django.db import migrations, models


def raise_default_quota(apps, schema_editor):
    settings = apps.get_model("core", "SiteSettings")
    settings.objects.filter(ai_daily_tokens__lte=1000000).update(ai_daily_tokens=1400000)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_raise_ai_daily_tokens_for_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='ai_daily_tokens',
            field=models.PositiveIntegerField(default=1400000),
        ),
        migrations.RunPython(raise_default_quota, migrations.RunPython.noop),
    ]
