# Generated by Django 5.2.17 on 2026-09-13 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("keywords", models.TextField(help_text="使用逗号分隔关键词与别名")),
                (
                    "status",
                    models.CharField(
                        choices=[("tracking", "追踪中"), ("paused", "已暂停"), ("ended", "已结束")],
                        default="tracking",
                        max_length=20,
                    ),
                ),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("overview", models.TextField(blank=True)),
                ("overview_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_scan", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("summary", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "time_basis",
                    models.CharField(
                        choices=[("occurred", "事件时间"), ("reported", "报道时间")],
                        default="reported",
                        max_length=20,
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("edited", models.BooleanField(default=False)),
                ("draft_key", models.CharField(max_length=200, null=True, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="nodes", to="events.event"
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "article",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="news.article"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("event", "article"), name="event_article_unique")
                ],
            },
        ),
        migrations.CreateModel(
            name="NodeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="events.node"
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_reports",
                        to="news.articleversion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("node", "version"), name="node_version_unique")
                ],
            },
        ),
    ]
