# Generated by Django 5.2.17 on 2026-09-13 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Briefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=150, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("legacy_text", models.TextField(blank=True)),
                ("imported", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-end", "-revision"],
            },
        ),
        migrations.CreateModel(
            name="BriefItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("title", models.TextField()),
                ("summary", models.TextField()),
                ("source", models.CharField(max_length=200)),
                ("url", models.TextField()),
                ("group_key", models.BigIntegerField(null=True)),
                (
                    "briefing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="briefs.briefing",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brief_items",
                        to="news.articleversion",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(fields=("briefing", "version"), name="brief_version_unique")
                ],
            },
        ),
    ]
